USE [master]
GO

/****** Object:  Database [TP1]    Script Date: 6/8/2020 11:01:39 AM ******/
CREATE DATABASE [TP1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP1', FILENAME = N'D:\rdsdbdata\DATA\TP1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TP1_log', FILENAME = N'D:\rdsdbdata\DATA\TP1_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TP1] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TP1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TP1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TP1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TP1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TP1] SET ARITHABORT OFF 
GO

ALTER DATABASE [TP1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TP1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TP1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TP1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TP1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TP1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TP1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TP1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TP1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TP1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TP1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TP1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TP1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TP1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TP1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TP1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TP1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TP1] SET RECOVERY FULL 
GO

ALTER DATABASE [TP1] SET  MULTI_USER 
GO

ALTER DATABASE [TP1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TP1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TP1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TP1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TP1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TP1] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TP1] SET  READ_WRITE 
GO

